# Generated by Django 3.2.25 on 2026-05-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
