# Generated by Django 3.2.25 on 2026-05-13 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letters', '0011_letter_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2, unique=True)),
                ('base_shipping_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_page', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_photo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['country_code'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state_province', models.CharField(blank=True, default='', max_length=120)),
                ('postal_code', models.CharField(max_length=30)),
                ('requested_delivery_date', models.DateField()),
                ('message_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('paid', 'Paid'),
                                                     ('printing', 'Printing'),
                                                     ('shipped', 'Shipped'),
                                                     ('delivered', 'Delivered')],
                                            default='paid', max_length=20)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=100)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('total_photos', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                              related_name='physical_letters', to='letters.countrypricing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='physical_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LetterAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='physical_letters/%Y/%m/%d/')),
                ('attachment_type', models.CharField(choices=[('text', 'Text'),
                                                              ('photo', 'Photo')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('physical_letter', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='attachments', to='letters.physicalletter')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
