# Generated by Django 3.2.25 on 2026-05-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0012_countrypricing_letterattachment_physicalletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrypricing',
            old_name='base_shipping_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='countrypricing',
            name='price_per_page',
        ),
        migrations.RemoveField(
            model_name='countrypricing',
            name='price_per_photo',
        ),
        migrations.AddField(
            model_name='countrypricing',
            name='country_name',
            field=models.CharField(default='Unknown', max_length=120),
            preserve_default=False,
        ),
    ]
