# Generated by Django 3.2.25 on 2026-05-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0013_auto_20260513_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalletter',
            name='total_printable_pages',
            field=models.PositiveIntegerField(default=0, help_text='User-specified total printable pages'),
        ),
        migrations.AlterField(
            model_name='physicalletter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('printing', 'Printing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='paid', max_length=20),
        ),
    ]
