# Generated by Django 3.2.25 on 2026-05-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0015_letter_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeleryTaskLog',
        ),
    ]
