# Generated by Django 3.2.25 on 2026-05-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0016_delete_celerytasklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='is_deleted',
        ),
    ]
