from django.urls import path

from .views import (
    balance_page,
    create_checkout_view,
    contact_page,
    contact_ticket_comment_view,
    concept_page,
    create_letter_page,
    dashboard_password_change_view,
    dashboard_secondary_emails_view,
    dashboard_view,
    delete_letter_view,
    edit_letter_view,
    faq_page,
    how_page,
    landing_page,
    lemonsqueezy_webhook_view,
    letters_page,
    payment_error_view,
    payment_success_view,
    privacy_page,
    terms_page,
)

urlpatterns = [
    path("", landing_page, name="landing-page"),
    path("letters/", letters_page, name="letters-page"),
    path("letters/create/", create_letter_page, name="letter-create-page"),
    path("letters/<int:letter_id>/delete/", delete_letter_view, name="letter-delete"),
    path("letters/<int:letter_id>/edit/", edit_letter_view, name="letter-edit"),
    path("vault/", letters_page, name="vault-page"),
    path("how/", how_page, name="how-page"),
    path("contact/", contact_page, name="contact-page"),
    path("why/", concept_page, name="why-page"),
    path("privacy/", privacy_page, name="privacy-page"),
    path("faq/", faq_page, name="faq-page"),
    path("terms/", terms_page, name="terms-page"),
    path("dashboard/", dashboard_view, name="dashboard_view"),
    path("balance/", balance_page, name="balance-page"),
    path("payment/checkout/", create_checkout_view, name="payment-checkout"),
    path("payment/success/", payment_success_view, name="payment-success"),
    path("payment/error/", payment_error_view, name="payment-error"),
    path(
        "payment/webhooks/lemonsqueezy/",
        lemonsqueezy_webhook_view,
        name="lemonsqueezy-webhook",
    ),
    path(
        "dashboard/password-change/",
        dashboard_password_change_view,
        name="dashboard-password-change",
    ),
    path(
        "dashboard/secondary-emails/",
        dashboard_secondary_emails_view,
        name="dashboard-secondary-emails",
    ),
    path(
        "contact/tickets/<int:ticket_id>/comment/",
        contact_ticket_comment_view,
        name="contact-ticket-comment",
    ),
]
